### ISSUE TITLE
Flux: bug on mapping

### ISSUE THREAD

**Issue by thelore85** [4GeeksAcademy/thelore85-contacts-list#1]
Hola Hector! tengo un bug:

Si llego a la view 'Contacts' desde el enlance del Navbar (Agenda) funciona!
Pero, si recargo la pagina, me da error... porque' pasa esto?

gracias!!

// FROM LINK
<img width="1698" alt="image" src="https://github.com/4GeeksAcademy/thelore85-contacts-list/assets/136301207/e5d87452-898c-47d7-a9e0-ee7b0cca885e">

// ERROR IF REFRESH THE PAGE
<img width="1703" alt="image" src="https://github.com/4GeeksAcademy/thelore85-contacts-list/assets/136301207/4fa83346-9a48-47ef-93a7-cef24fa168a4">

**Comment by hchocobar** [comment]
@thelore85 cuando haces un reload, la variable `data` o no existe o no es un array. Ese es el motivo por el cual te da error el .map (que es un método de un array).

Recuerda que al hacer un reload de la página, el dom-virtual se pierde, y con ello los estados, store, (etc) de react. Para solucionar esto utilizamos el localSotrage o el sesionStorage del browser.
